import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Activity, AlertTriangle, Shield, Database, Lock, Fingerprint, MapPin, CheckCircle2 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { StatsGrid } from '../components/Dashboard/StatsGrid';
import { RecentTestsTable } from '../components/Dashboard/RecentTestsTable';

export default function DashboardPage() {
  const { operator, records, stats } = useApp();
  const navigate = useNavigate();

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      {/* Page header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-xl font-bold text-slate-100">Command Centre</h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Field operations overview · {operator?.id} · {new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </div>
        <button
          onClick={() => navigate('/new-test')}
          className="btn-primary text-sm"
        >
          <Plus className="w-4 h-4" />
          New Field Test
        </button>
      </div>

      {/* Disclaimer banner */}
      <div className="flex items-start gap-3 px-4 py-3 rounded-lg bg-amber-900/10 border border-amber-700/20">
        <AlertTriangle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-amber-400/80 leading-relaxed">
          All results displayed are <strong>presumptive field results</strong> generated by AI-assisted colorimetric analysis.
          These results are <strong>not</strong> laboratory confirmations and must not be used as the sole basis for enforcement action.
          Laboratory confirmation is required before any legal proceedings.
        </p>
      </div>

      {/* KPI grid */}
      <StatsGrid stats={stats} />

      {/* Quick action cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <QuickAction
          icon={<Plus className="w-5 h-5 text-indigo-400" />}
          title="Start New Field Test"
          description="Begin a new colorimetric field test with guided capture workflow"
          onClick={() => navigate('/new-test')}
          accent="border-indigo-700/30 hover:border-indigo-500/50 hover:bg-indigo-900/10"
        />
        <QuickAction
          icon={<Activity className="w-5 h-5 text-emerald-400" />}
          title="Verify Evidence"
          description="Verify the cryptographic integrity of a sealed evidence record"
          onClick={() => navigate('/verify')}
          accent="border-emerald-700/30 hover:border-emerald-500/50 hover:bg-emerald-900/10"
        />
        <QuickAction
          icon={<AlertTriangle className="w-5 h-5 text-amber-400" />}
          title="Demo: Tamper Detection"
          description="Demonstrate the WOW moment — tamper evidence and run verification"
          onClick={() => navigate('/verify?demo=tamper')}
          accent="border-amber-700/30 hover:border-amber-500/50 hover:bg-amber-900/10"
        />
      </div>

      {/* Security & Evidence Status panel */}
      <SecurityDashboard />

      {/* Recent tests */}
      <RecentTestsTable records={records} />
    </div>
  );
}

function SecurityDashboard() {
  const { user, operator } = useApp();
  const checks = [
    {
      icon: <Lock className="w-4 h-4" />,
      label: 'Authenticated Operator',
      status: !!user,
      detail: user ? `${user.username} · ${user.role}` : 'Not authenticated',
      color: 'text-emerald-400',
    },
    {
      icon: <Database className="w-4 h-4" />,
      label: 'Database',
      status: true,
      detail: 'SQLite · WAL journal · Persistent',
      color: 'text-emerald-400',
    },
    {
      icon: <Shield className="w-4 h-4" />,
      label: 'Active Session',
      status: !!operator,
      detail: operator ? `${operator.sessionId} · JWT (8 h TTL)` : 'No session',
      color: 'text-emerald-400',
    },
    {
      icon: <Fingerprint className="w-4 h-4" />,
      label: 'Evidence Sealing',
      status: true,
      detail: 'Dual SHA-256 · Combined evidence hash',
      color: 'text-emerald-400',
    },
    {
      icon: <CheckCircle2 className="w-4 h-4" />,
      label: 'Audit Trail',
      status: true,
      detail: 'SQLite · Immutable append-only log',
      color: 'text-emerald-400',
    },
    {
      icon: <MapPin className="w-4 h-4" />,
      label: 'Location Capture',
      status: true,
      detail: 'navigator.geolocation · SIMULATED if denied',
      color: 'text-indigo-400',
    },
    {
      icon: <Lock className="w-4 h-4" />,
      label: 'Password Storage',
      status: true,
      detail: 'Hashed with bcryptjs (12 rounds) · Never plaintext',
      color: 'text-emerald-400',
    },
    {
      icon: <Shield className="w-4 h-4" />,
      label: 'Login Security',
      status: true,
      detail: 'Timing-safe bcrypt compare · No credential enumeration',
      color: 'text-emerald-400',
    },
  ];

  return (
    <div className="panel-elevated p-5">
      <div className="flex items-center gap-2 mb-4">
        <Shield className="w-4 h-4 text-indigo-400" />
        <h2 className="text-sm font-semibold text-slate-200">Security &amp; Evidence Status</h2>
        <span className="ml-auto text-[10px] text-emerald-400 font-mono bg-emerald-900/20 border border-emerald-700/20 px-2 py-0.5 rounded">
          ALL SYSTEMS OPERATIONAL
        </span>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {checks.map(c => (
          <div key={c.label} className="flex items-start gap-3 bg-slate-800/30 rounded-lg p-3 border border-slate-700/20">
            <div className={`mt-0.5 flex-shrink-0 ${c.color}`}>{c.icon}</div>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <span className="text-xs font-medium text-slate-200">{c.label}</span>
                {c.status
                  ? <CheckCircle2 className="w-3 h-3 text-emerald-500 flex-shrink-0" />
                  : <AlertTriangle className="w-3 h-3 text-amber-400 flex-shrink-0" />
                }
              </div>
              <p className="text-[11px] text-slate-500 mt-0.5 leading-relaxed">{c.detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function QuickAction({ icon, title, description, onClick, accent }: {
  icon: React.ReactNode;
  title: string;
  description: string;
  onClick: () => void;
  accent: string;
}) {
  return (
    <button
      onClick={onClick}
      className={`glass-panel p-4 text-left cursor-pointer transition-all duration-200 border ${accent} group`}
    >
      <div className="flex items-start gap-3">
        <div className="mt-0.5">{icon}</div>
        <div>
          <div className="text-sm font-medium text-slate-200 group-hover:text-white">{title}</div>
          <div className="text-xs text-slate-500 mt-1 leading-relaxed">{description}</div>
        </div>
      </div>
    </button>
  );
}
